# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: build

# Trigger workflow on any push or pull request.
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  lint:
    name: Check code with formatter and linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache Node packages
        uses: actions/cache@v2
        with:
          path: node_modules
          key: >-
            node-16_${{ runner.os }}_npm-${{ hashFiles('package-lock.json') }}
      - name: Install Node packages
        run: npm install
      - name: Check format of configuration files
        run: npm run lint:check

  test-unit:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache Node packages
        uses: actions/cache@v2
        with:
          path: node_modules
          key: >-
            node-16_${{ runner.os }}_npm-${{ hashFiles('package-lock.json') }}
      - name: Install Node packages
        run: npm install
      - name: Run unit tests
        run: npm run test:unit

  test-integration:
    # GitHub contains function does not support literal arrays. For more
    # information, visit
    # https://github.community/t/passing-an-array-literal-to-contains-function-causes-syntax-error/17213.
    if: >-
      ${{ !contains(fromJson('["refs/heads/develop", "refs/heads/main",
      "refs/heads/master"]'), github.ref) }}
    name: Run integration test suite for Chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v2
        with:
          node-version: 16
      # Cypress actions installs and caches Node packages.
      - name: Run integration tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run vue:serve
          wait-on: http://localhost:8080/
      - name: Upload screenshots if test suite fails
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          if-no-files-found: warn
          name: cypress-logs-chrome
          path: |
            cypress/screenshots
            cypress/videos
