# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: test

# Trigger workflow on push or pull request to the develop, main, and master
# branches.
on:
  pull_request:
    branches:
      - develop
      - main
      - master
  push:
    branches:
      - develop
      - main
      - master

jobs:
  test-integration:
    name: Run integration test suite for ${{ matrix.browser }}
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v2
        with:
          node-version: 16
      # Cypress actions installs and caches Node packages.
      - name: Run integration tests
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          start: npm run vue:serve
          wait-on: http://localhost:8080/
      - name: Upload screenshots if test suite fails
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          if-no-files-found: warn
          name: cypress-logs-${{ matrix.browser }}
          path: |
            cypress/screenshots
            cypress/videos
